base.url=http://app:8080/Docker_backup

backup.url=/usr/local/tomcat/webapps/Docker_backup/backup_history.txt

backup.source.path=/data/tmp
backup.destination.path=/data/backup

backup.nosource.path=/data/source1

backup.filesource.path=/data/source/tempfile.txt
    
backup.invalid.source.path=@#$%^&*

backup.new.source.path=/data/test
backup.auto.destination.base.path=/data/a_backup

backup.example.source.path=/data/source
backup.file.destination.path=/data/backup/tempfile.txt

backup.random.source.path=sgrfdfdfds
backup.random.destination.path=dsgfsdrf

backup.Sql.source.path=DROP TABLE Users;

backup.directory.source.path=../../passwd

backup.symlink.source.path=/data/etc_link

backup.invalid.destination.path=@#$%^&*

backup.empty.source.path=/data/empty-source

backup.unsupported.source.path=/data/unsupported_files

backup.minlength.source.path=/data/
backup.minlength.destination.path=/data/

backup.longpath.base=/data/
backup.longpath.length=260
backup.long.dest.base=/data/

backup.temp.source.path=/data/temp
backup.temp.destination.path=/data/temp

backup.res.source.path=/app/restricted/source
backup.res.destination.path=/root/backup

backup.large.source.path=/data/LargeData

backup.new.destination.path=/data/new_backup
backup.placeholder.source.path=/home/user/source
backup.placeholder.destination.path=/home/user/backup

backup.temp1.source.path=/data/temp1
